# Generated by Django 2.2.6 on 2019-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemforsale',
            name='itemsku',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
