# Generated by Django 2.2.6 on 2019-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_itemforsale_itemsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemforsale',
            name='price_for_stripe',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
